server:
  port: 8085

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USUARIO-SERVICE
        uri: lb://USUARIO-SERVICE
        predicates:
          - Path=/usuarios/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
            - Path=/hoteles/**,/staffs/**

      - id: CALIFICACION-SERVICE
        uri: lb://CALIFICACION-SERVICE
        predicates:
          - Path=/calificaiones/**
          -
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/auth/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka