server:
  port: 8082

spring:
  application:
    name: USUARIO-SERVICE

  config:
    import: optional:configserver:http://localhost:8086

  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect