server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: postgres
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8086