server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sujeto-17/microservicios-config
          clone-on-start: true